/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation("com.google.auto.service:auto-service:1.0.1")
    implementation("net.pearx.kasechange:kasechange-jvm:1.3.0")
    implementation("com.squareup:kotlinpoet:1.10.2")
    implementation("io.vertx:vertx-rx-java2:4.2.5")
}

description = "lib-annotation-processor"
