/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation("io.vertx:vertx-auth-jwt:4.2.5")
    implementation("io.vertx:vertx-core:4.2.5")
    implementation("io.vertx:vertx-web:4.2.5")
    implementation("io.vertx:vertx-web-client:4.2.5")
    implementation("io.vertx:vertx-auth-oauth2:4.2.5")
    implementation("io.vertx:vertx-auth-common:4.2.5")
    implementation("org.bitbucket.b_c:jose4j:0.7.12")
    implementation(project(":lib-service-utils"))
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":plugin-metastore-mongo"))
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
    testImplementation("uk.org.webcompere:system-stubs-jupiter:1.1.0")
}

description = "pub-auth-service"
