/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation("io.vertx:vertx-rx-java2:4.2.5")
    implementation("org.mindrot:jbcrypt:0.4")
    implementation("com.github.akarnokd:rxjava3-bridge:3.0.2")
    testImplementation(project(":plugin-metastore-mongo"))
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
}

description = "plugin-accessmanager-basic"
