/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation("io.vertx:vertx-lang-kotlin:4.2.5")
    implementation(project(":lib-pulsar-utils"))
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":plugin-metastore-mongo"))
    implementation(project(":plugin-ratelimiter-gubernator"))
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
    testImplementation(project(":lib-oblx-client"))
    testImplementation(project(":pub-auth-service"))
}

description = "pub-ingest-service"
