/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation("io.vertx:vertx-mongo-client:4.2.5")
    implementation("io.vertx:vertx-rx-java2:4.2.5")
}

description = "lib-mongo-utils"
