/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-definitions"))
    implementation("io.vertx:vertx-web-client:4.2.5")
    implementation("com.github.davidmoten:rxjava2-extras:0.1.38")
}

description = "lib-oblx-client"
