/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":pub-auth-service"))
    implementation(project(":pub-ingest-service"))
    implementation(project(":int-sink-service"))
    implementation(project(":int-dataset-streamer"))
    implementation(project(":pub-query-service"))
    implementation(project(":pub-catalog-service"))
    implementation(project(":pub-streaming-service"))
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":pub-ngsi-service"))
    implementation(project(":pub-monitor-service"))
    implementation(project(":pub-export-service"))
    implementation(project(":plugin-ratelimiter-gubernator"))
    implementation(project(":pub-issue-service"))
    implementation(project(":int-stats-collector"))
    implementation(project(":plugin-monitoring-prometheus"))
    implementation("org.apache.pulsar:pulsar-client-admin:2.10.1")
    implementation(project(":pub-dcat-service"))
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
}

description = "monolith"
