/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation(project(":plugin-metastore-mongo"))
    implementation("org.apache.jena:jena-core:3.14.0")
    implementation("org.apache.jena:jena-arq:3.14.0")
    implementation("commons-validator:commons-validator:1.7")
}

description = "pub-dcat-service"
