version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar:2.9.2
    ports:
      - 6650:6650
      - 8086:8080
    command: bin/pulsar standalone
  mongodb:
    image: mongo:4.2
    ports:
    - 27017:27017
  clickhouse:
    image: clickhouse/clickhouse-server:22.5
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - '../plugin-datastore-clickhouse/initdb:/docker-entrypoint-initdb.d'
      - '../plugin-datastore-clickhouse/ch-server-config/config.xml:/etc/clickhouse-server/config.xml'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  redis:
    image: 'bitnami/redis:6.0'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  gubernator:
    image: ghcr.io/mailgun/gubernator:v2.0.0-rc.23
    command: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      # The address that is advertised to other peers
      - GUBER_ADVERTISE_ADDRESS=gubernator:81
      # A comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator
      #- GUBER_DATA_CENTER=us-east-1
    ports:
      - "9081:81"
      - "9080:80"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - '../prometheus.yml:/etc/prometheus/prometheus.yml'
