/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation(project(":lib-pulsar-utils"))
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":plugin-metastore-mongo"))
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
    testImplementation(project(":lib-oblx-client"))
    testImplementation(project(":pub-auth-service"))
    testImplementation(project(":pub-catalog-service"))
    testImplementation(project(":plugin-ratelimiter-gubernator"))
    testImplementation(project(":plugin-datastore-clickhouse"))
    testImplementation("uk.org.webcompere:system-stubs-jupiter:1.1.0")
}

description = "pub-streaming-service"
