/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation("io.vertx:vertx-web-graphql:4.2.5")
    implementation("com.graphql-java:graphql-java-extended-scalars:18.1")
    implementation("com.github.akarnokd:rxjava2-jdk8-interop:0.3.7")
    implementation(project(":plugin-datastore-clickhouse"))
    implementation(project(":plugin-metastore-mongo"))
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":plugin-ratelimiter-gubernator"))
    implementation("org.apache.tika:tika-core:1.23")
    implementation(project(":lib-pulsar-utils"))
    implementation(project(":plugin-monitoring-prometheus"))
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
}

description = "pub-catalog-service"
