/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation("io.vertx:vertx-rx-java2:4.2.5")
    implementation("org.apache.pulsar:pulsar-client:2.10.1")
    implementation("org.apache.pulsar:pulsar-client-admin:2.10.1")
    implementation("com.github.akarnokd:rxjava2-jdk8-interop:0.3.7")
    implementation("com.github.davidmoten:rxjava2-extras:0.1.38")
    implementation("com.github.ben-manes.caffeine:caffeine:2.8.1")
}

description = "lib-pulsar-utils"
