apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  configuration:
    clusters:
      - name: "oblx-data"
        templates:
          dataVolumeClaimTemplate: data-storage-vc-template
          logVolumeClaimTemplate: log-storage-vc-template
          podTemplate: pod-template-with-volumes
        # Change to desired
        layout:
          shardsCount: 2
          replicasCount: 2
    zookeeper:
      nodes:
        # Check correct URL/port for your installation!
        - host: zookeeper-headless.clickhouse.svc.cluster.local
          port: 2181
  templates:
    podTemplates:
      - name: pod-template-with-volumes
        podDistribution:
          - type: ShardAntiAffinity
          - type: MaxNumberPerNode
            number: 2
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.3
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              # Change according to your usage and resource limitations
              resources:
                requests:
                  memory: 1Gi
                  cpu: 0.5
                limits:
                  memory: 4Gi
                  cpu: 1
    # Change your storageclasses and if desired sizes
    volumeClaimTemplates:
      - name: data-storage-vc-template
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: ""
          resources:
            requests:
              storage: 200Gi
      - name: log-storage-vc-template
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: ""
          resources:
            requests:
              storage: 50Gi
