# Docker Registry secret for the gitlab repo
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commons.fullname" . }}-docker-reg-creds
  labels:
    {{- include "commons.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "commons.imagePullSecret" . }}
