{{ include "oblx-service-template.ingressRoute" . }}
    middlewares:
      - name: add-slash-catalog
      - name: strip-prefix-catalog
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-slash-catalog
spec:
  redirectRegex:
    regex: ^(.*{{ $.Values.basePath }})$
    replacement: ${1}/
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-catalog
spec:
  stripPrefix:
    prefixes:
      - "{{ $.Values.basePath }}"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-route
spec:
  {{- if .Values.tls.enabled }}
  entryPoints:
  - websecure
  tls:
    {{- if .Values.tls.secretName }}
    secretName: {{ .Values.tls.secretName }}
    {{- else if .Values.tls.certResolver }}
    certResolver: {{ .Values.tls.certResolver }}
    {{- end }}
  {{- else }}
  entryPoints:
  - web
  {{- end }}
  routes:
  - match: Path(`/`)
    kind: Rule
    services:
    - name: {{ include "oblx-service-template.fullname" . }}
      port: {{ .Values.service.port }}
    middlewares:
    - name: redirect-to-catalog
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-catalog
spec:
  redirectRegex:
    regex: ^(.*)$
    replacement: /catalog/
