/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-definitions"))
    implementation("io.vertx:vertx-config:4.2.5")
    implementation("io.vertx:vertx-mail-client:4.2.5")
    implementation("io.vertx:vertx-lang-kotlin:4.2.5")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3")
    implementation("com.github.davidmoten:rxjava2-extras:0.1.38")
    implementation("com.github.ben-manes.caffeine:caffeine:2.8.1")
    implementation("org.locationtech.spatial4j:spatial4j:0.8")
    implementation("org.locationtech.jts:jts-core:1.15.0")
    implementation("org.redisson:redisson:3.17.4")
    implementation("com.uber.rxdogtag:rxdogtag:1.0.1")
    implementation("io.vertx:vertx-micrometer-metrics:4.2.5")
    implementation("io.micrometer:micrometer-registry-prometheus:1.7.1")
    implementation("com.github.akarnokd:rxjava3-bridge:3.0.2")
}

description = "lib-service-utils"
