/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation(project(":lib-oblx-client"))
    implementation("io.vertx:vertx-web-client:4.2.5")
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":plugin-metastore-mongo"))
    implementation(project(":plugin-datastore-clickhouse"))
    implementation("com.google.guava:guava:31.1-jre")
    implementation("com.github.kkuegler:human-readable-ids-java:0.1.1")
}

description = "pub-monitor-service"
