/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation(project(":lib-pulsar-utils"))
    implementation(project(":plugin-metastore-mongo"))
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":plugin-datastore-clickhouse"))
    implementation("net.lingala.zip4j:zip4j:2.10.0")
    implementation("org.apache.commons:commons-csv:1.9.0")
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
    testImplementation(project(":lib-test-utils"))
}

description = "pub-export-service"
