apiVersion: v2
name: obelisk
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 22.7.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "22.7.2"

dependencies:
  - name: oblx-service-template
    repository: file://../oblx-service-template
    version: ~22.7.2
  - name: int-dataset-streamer
    repository: file://../int-dataset-streamer
    version: ~22.7.2
    condition: int-dataset-streamer.enabled
  - name: int-sink-service
    repository: file://../int-sink-service
    version: ~22.7.2
    condition: int-sink-service.enabled
  - name: int-stats-collector
    repository: file://../int-stats-collector
    version: ~22.7.2
    condition: int-stats-collector.enabled
  - name: pub-auth-service
    repository: file://../pub-auth-service
    version: ~22.7.2
    condition: pub-auth-service.enabled
  - name: pub-catalog-service
    repository: file://../pub-catalog-service
    version: ~22.7.2
    condition: pub-catalog-service.enabled
  - name: pub-export-service
    repository: file://../pub-export-service
    version: ~22.7.2
    condition: pub-export-service.enabled
  - name: pub-ingest-service
    repository: file://../pub-ingest-service
    version: ~22.7.2
    condition: pub-ingest-service.enabled
  - name: pub-issue-service
    condition: pub-issue-service.enabled
    repository: file://../pub-issue-service
    version: ~22.7.2
  - name: pub-monitor-service
    repository: file://../pub-monitor-service
    version: ~22.7.2
    condition: pub-monitor-service.enabled
  - name: pub-query-service
    repository: file://../pub-query-service
    version: ~22.7.2
    condition: pub-query-service.enabled
  - name: pub-streaming-service
    repository: file://../pub-streaming-service
    version: ~22.7.2
    condition: pub-streaming-service.enabled
  - name: web-apiconsole
    repository: file://../web-apiconsole
    version: ~22.7.2
    condition: web-apiconsole.enabled
  - name: web-catalog
    repository: file://../web-catalog
    version: ~22.7.2
    condition: web-catalog.enabled
