apiVersion: v2
name: pub-ingest-service
description: Helm chart for the public Ingest Service of the Obelisk platform.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: v22.7.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v22.7.1"

dependencies:
  - name: oblx-service-template
    repository: file://../oblx-service-template
    version: ~v22.7.1
