/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-definitions"))
    implementation("io.vertx:vertx-web-client:4.2.5")
}

description = "plugin-monitoring-prometheus"
