/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-annotation-processor"))
    implementation("io.vertx:vertx-core:4.2.5")
    implementation("io.vertx:vertx-rx-java2:4.2.5")
    implementation("io.vertx:vertx-web:4.2.5")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3")
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
}

description = "lib-definitions"
