/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation(project(":lib-pulsar-utils"))
    implementation("io.vertx:vertx-web-client:4.2.5")
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":plugin-metastore-mongo"))
    implementation(project(":plugin-datastore-clickhouse"))
    implementation("com.github.jsonld-java:jsonld-java:0.13.0")
    implementation("commons-validator:commons-validator:1.6")
    implementation(project(":plugin-ratelimiter-gubernator"))
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
    testImplementation(project(":int-sink-service"))
    testImplementation(project(":pub-auth-service"))
    testImplementation(project(":lib-oblx-client"))
    testImplementation("uk.org.webcompere:system-stubs-jupiter:1.1.0")
}

description = "pub-ngsi-service"
