/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-definitions"))
    implementation(project(":lib-service-utils"))
    implementation("io.vertx:vertx-lang-kotlin:4.2.5")
    implementation("io.vertx:vertx-jdbc-client:4.2.5")
    implementation("com.clickhouse:clickhouse-jdbc:0.3.2-patch6")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    implementation("org.apache.httpcomponents:httpmime:4.5.13")
    implementation("com.google.auto.service:auto-service:1.0.1")
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
    testImplementation("ch.hsr:geohash:1.4.0")
    testImplementation(project(":lib-test-utils"))
}

description = "plugin-datastore-clickhouse"
