# Additional config for the Microservices (is mounted along the Obelisk Base configuration)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pub-export-service.fullname" . }}-config
data:
  HTTP_BASE_PATH: "{{ .Values.basePath }}"
  EXPORTS_DIR: "{{ .Values.persistence.mountPath }}"
  EXPORTS__CHUNK_SIZE: "{{ .Values.config.exportChunkSize }}"
  MAX_RECORDS_PER_JOB: "{{ .Values.config.maxEventsPerJob }}"
