/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-definitions"))
    implementation(project(":lib-mongo-utils"))
    testImplementation("io.vertx:vertx-junit5-rx-java2:4.2.5")
    testImplementation("org.ajbrown:name-machine:1.0.0")
}

description = "plugin-metastore-mongo"
