/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation(project(":lib-mongo-utils"))
    implementation(project(":plugin-accessmanager-basic"))
    implementation(project(":plugin-metastore-mongo"))
}

description = "pub-issue-service"
