/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idlab.obelisk.java-conventions")
}

dependencies {
    implementation(project(":lib-service-utils"))
    implementation(project(":plugin-datastore-clickhouse"))
    implementation(project(":plugin-metastore-mongo"))
}

description = "int-stats-collector"
