name: Build docs

on:
  workflow_call:
    inputs:
      release:
        description: Should a release be triggered.
        required: false
        type: boolean
        default: false
      version:
        description: Version to be released
        required: false
        type: string

permissions:
  contents: read
  packages: write

env:
  VERSION: ${{ inputs.version }}
  registry: ghcr.io

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest'
          requirements: 'documentation/requirements.txt'
          configfile: 'documentation/mkdocs.yml'
      - name: Move site to docker/
        run: |
          cp -R documentation/site documentation/docker/site
      - name: Kaniko build
        uses: aevea/action-kaniko@v0.10.0
        if: ${{ inputs.release }}
        with:
          image: docs
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
          registry: ${{ env.registry }}
          cache: true
          cache_registry: aevea/cache
          tag: ${{ inputs.version }}
          path: documentation/docker/
