name: Maven workflow

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/idlab/obelisk
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Compile
      run: mvn -B -ntp clean compile -DskipTests
    - name: Setup the docker-compose test environment
      run: docker-compose up -d
    - name: Check the test environment
      run: docker ps -a
    - name: Run test
      run: mvn test -B -ntp --fail-at-end
    - name: Surefire Report
      uses: ScaCap/action-surefire-report@v1.0.5
