name: Maven workflow

on:
  pull_request_target:
    branches:
      - main
      - next
    paths:
     - '**/pom.xml'
     - '**/src/main/kotlin/**'
     - '**/test/kotlin/**'
     - '**/src/main/java/**'
     - '**/test/java/**'
  pull_request:
    branches:
      - main
      - next
    paths:
     - '**/pom.xml'
     - '**/src/main/kotlin/**'
     - '**/test/kotlin/**'
     - '**/src/main/java/**'
     - '**/test/java/**'

jobs:
  maven-build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.OBLX_PAT || github.token }}
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Compile
      run: mvn -B -ntp clean compile -DskipTests
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        key: docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}-{hash}
        restore-keys: |
          docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}-{hash}
          docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
          docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}
          docker-layer-caching-${{ github.workflow }}
          docker-layer-caching-
    - run: docker-compose -f .test/docker-compose.yml up -d
    - name: Run test
      run: mvn test -B -ntp --fail-at-end
    - name: Surefire Report
      if: ${{ always() }}
      continue-on-error: true
      uses: ScaCap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.OBLX_PAT }}
