name: Maven workflow

on:
  workflow_call:
    inputs:
      release:
        description: Should a release be triggered.
        required: false
        type: boolean
        default: false
      version:
        required: false
        type: string

jobs:
  maven-build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OBLX_PAT || secrets.github_token }}
      - name: Pull when releasing
        if: ${{ inputs.release }}
        run: git pull
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Compile
        run: mvn -B -ntp clean compile -DskipTests
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}-{hash}
            docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
            docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}
            docker-layer-caching-${{ github.workflow }}
            docker-layer-caching-
      - run: docker-compose -f .test/docker-compose.yml up -d
      - name: Run test
        run: mvn test -B -ntp --fail-at-end
      - name: Surefire Report
        if: ${{ always() }}
        continue-on-error: true
        uses: ScaCap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.OBLX_PAT || secrets.GITHUB_TOKEN }}

  maven-release:
    runs-on: ubuntu-latest
    needs: maven-build
    if: ${{ inputs.release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OBLX_PAT || secrets.github_token }}
      - run: git pull
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: echo ${{ inputs.version }}
      - env:
          VERSION: ${{ inputs.version }}
        name: Deploy packages and build containers
        run: mvn -B -ntp -DskipTests -DuseGitHubPackages=true compile jib:dockerBuild -Djib.to.tags=${VERSION%.*}
