name: Maven workflow

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  maven-build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Compile
      run: mvn -B -ntp clean compile -DskipTests
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        key: obelisk-docker-cache-{hash}
        restore-keys: |
          obelisk-docker-cache-
    - uses: isbang/compose-action@v1.0.0
      with:
        compose-file: './.test/docker-compose.yml'
        down-flags: '--volumes'
    - name: Check the test environment
      run: docker ps -a
    - name: Run test
      run: mvn test -B -ntp --fail-at-end
    - name: Surefire Report
      if: ${{ always() }}
      continue-on-error: true
      uses: ScaCap/action-surefire-report@v1
