name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main
      - next
    paths:
      - 'charts/**'

jobs:
  lint-test:
    uses: ./.github/workflows/helm.yaml
    with:
      release: false
