name: Maven compile and test

on:
  pull_request:
    branches:
      - main
      - next
    paths:
     - '**/pom.xml'
     - '**/src/main/kotlin/**'
     - '**/test/kotlin/**'
     - '**/src/main/java/**'
     - '**/test/java/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  compile-test:
    uses: ./.github/workflows/maven.yaml
    with:
      release: false
  surefire-report:
    runs-on: ubuntu-latest
    needs: compile-test
    steps:
      - name: Download Surefire Report
        uses: actions/download-artifact@v2
        with:
          name: surefire-reports
          path: surefire-reports
      - name: Surefire Report
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1
        with:
          github_token: secrets.GITHUB_TOKEN
          report_paths: surefire-reports
