name: Maven compile and test

on:
  pull_request:
    branches:
      - main
      - next
    paths:
     - '**/pom.xml'
     - '**/src/main/kotlin/**'
     - '**/test/kotlin/**'
     - '**/src/main/java/**'
     - '**/test/java/**'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
# TODO: split up compile and release maven workflows
  compile-test:
    uses: ./.github/workflows/maven.yaml
    with:
      release: false
  surefire-report:
    runs-on: ubuntu-latest
    needs: compile-test
    if: ${{ success() || failure() }} # always run, but obey manual cancellation
    steps:
      - name: Download Surefire Report
        uses: actions/download-artifact@v2
        with:
          name: surefire-reports
          path: surefire-reports
      - name: Surefire Report
        uses: mikepenz/action-junit-report@v3
        with:
          github_token: secrets.GITHUB_TOKEN
          report_paths: surefire-reports/**/target/surefire-reports/TEST-*.xml
