name: Maven compile and test

on:
  pull_request:
    branches:
      - main
      - next
    paths:
     - '**/pom.xml'
     - '**/src/main/kotlin/**'
     - '**/test/kotlin/**'
     - '**/src/main/java/**'
     - '**/test/java/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  compile-test:
    uses: ./.github/workflows/maven.yaml
    with:
      release: false
