name: Release

on:
  push:
    branches:
      - main

jobs:
  check-release:
    outputs:
      lc: ${{ steps.changelog-lines.outputs.lc }}
      version: ${{ steps.bumper.outputs.new_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OBLX_PAT || secrets.github_token }}
          fetch-depth: 0
      - name: Run bumper
        id: bumper
        uses: tomerfi/version-bumper-action@1.2.2
        with:
          changelog: true
          bumpoverride: patch
      - id: changelog-lines
        run: |
          mv changelog-${{ steps.bumper.outputs.new_version }}.md changelog-new.md
          echo "lc=$(wc -l changelog-new.md | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
      - if: ${{ steps.changelog-lines.outputs.lc > 2 }}
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: changelog-new.md
          retention-days: 1

  version-bump:
    needs: check-release
    runs-on: ubuntu-latest
    if: ${{ needs.check-release.outputs.lc > 2 }}
    permissions:
      contents: write
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OBLX_PAT || secrets.github_token }}
          fetch-depth: 0
      - name: Configure committer
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.2

      # Strips the version and checks if a CalVer bump is needed
      - name: check CalVer bump
        env:
          VERSION: ${{ needs.check-release.outputs.version }}
        id: bump
        run: |
          MAJOR_MINOR=$(echo $VERSION | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2/')
          CALVER=$(date +%y.%-m)
          if [[ $MAJOR_MINOR != $CALVER ]]; then
            echo "version=$CALVER.0" >> $GITHUB_OUTPUT
          else
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      # Download changelog artifact
      - uses: actions/download-artifact@v3
        with:
          name: changelog
          path: changelog-new.md

      - name: Merge changelog and fix formatting
        run: |
          sed -E 's/([\[\.]v)([0-9]+)\.([0-9]+)\.([0-9]+)/\1'"$VERSION"'/gm' -i changelog-new.md
          sed -E 's/### \[/## [/' -i changelog-${{ steps.bump.outputs.version }}.md
          sed -e "4r changelog-new.md" -i CHANGELOG.md
          rm changelog-new.md

      # - name: Run bumper
      #   id: bumper
      #   uses: tomerfi/version-bumper-action@1.2.2
      #   with:
      #     changelog: true
      #     bumpoverride: patch
      # - run: |
      #     mv changelog-${{ steps.bumper.outputs.new_version }}.md changelog-${{ steps.bump.outputs.version }}.md

      # Bumps Helm and Maven versions
      - env:
          VERSION: ${{ steps.bump.outputs.version }}
        run: |
          ./mvnw versions:set -q -B -DnewVersion=$VERSION
          ./charts/bump-version.sh $VERSION
          ./charts/update-dependencies.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: "chore(release): changelog and version bumps [skip ci]"

  helm-release:
    needs: version-bump
    if: ${{ needs.check-release.outputs.lc > 2 }}
    uses: ./.github/workflows/helm.yaml
    with:
      release: true

  maven-release:
    needs: version-bump
    if: ${{ needs.check-release.outputs.lc > 2 }}
    uses: ./.github/workflows/maven.yaml
    with:
      release: true
      version: ${{ needs.version-bump.outputs.version }}
    secrets: inherit

# When Maven, Helm and Yarn releases are completed, then we can tag the release commit.
  finalize:
    runs-on: ubuntu-latest
    needs:
      - version-bump
      - maven-release
      - helm-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OBLX_PAT || secrets.github_token }}
      - name: Configure committer
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - env:
          VERSION: ${{ needs.version-bump.outputs.version }}
        run: |
          git pull
          git tag -a "v$VERSION" -m "Obelisk v$VERSION"
          git push origin --follow-tags
