name: Release dev Version
on:
  push:
    branches:
      - next

jobs:
  # version:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     version: ${{ steps.version.outputs.version }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.OBLX_PAT || secrets.github_token }}
  #         fetch-depth: 0
  #     - name: Get current version
  #       id: version
  #       run: echo "version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

  npm-catalog:
    # needs: version
    uses: ./.github/workflows/npm.yaml
    with:
      module: web-catalog
      base_href: catalog
      release: true
      version: next

  npm-apiconsole:
    # needs: version
    uses: ./.github/workflows/npm.yaml
    with:
      module: web-apiconsole
      base_href: apiconsole
      release: true
      version: next

  mvn-backend:
    # needs: version
    uses: ./.github/workflows/maven.yaml
    with:
      release_image: true
      version: next
