name: Comment on PR with Surefire Report

on:
  workflow_run:
    workflows:
     - "Maven compile and test"
     - "Maven release"
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Download Surefire Report
        uses: actions/download-artifact@v2
        with:
          name: surefire-reports
          path: surefire-reports
      - name: Surefire Report
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1
        with:
          github_token: secrets.GITHUB_TOKEN
